export const ARABIC_TEAM_MAP: Record<string, string> = {
  // Premier League
  'Arsenal': 'أرسنال',
  'Aston Villa': 'أستون فيلا',
  'Bournemouth': 'بورنموث',
  'Brentford': 'برينتفورد',
  'Brighton': 'برايتون',
  'Burnley': 'بيرنلي',
  'Chelsea': 'تشيلسي',
  'Crystal Palace': 'كريستال بالاس',
  'Everton': 'إيفرتون',
  'Fulham': 'فولهام',
  'Liverpool': 'ليفربول',
  'Luton': 'لوتون تاون',
  'Manchester City': 'مانشستر سيتي',
  'Manchester United': 'مانشستر يونايتد',
  'Newcastle': 'نيوكاسل يونايتد',
  'Nott\'m Forest': 'نوتينغهام فورست',
  'Nottingham Forest': 'نوتينغهام فورست',
  'Sheffield Utd': 'شيفيلد يونايتد',
  'Tottenham': 'توتنهام هوتسبير',
  'West Ham': 'وست هام يونايتد',
  'Wolves': 'وولفرهامبتون',
  'Wolverhampton Wanderers': 'وولفرهامبتون',
  'Sunderland': 'سندرلاند',
  'Leeds': 'ليدز يونايتد',

  // La Liga & Segunda
  'Alaves': 'ألافيس',
  'Almeria': 'ألميريا',
  'Athletic Club': 'أتلتيك بيلباو',
  'Atletico Madrid': 'أتلتيكو مدريد',
  'Barcelona': 'برشلونة',
  'Cadiz': 'قادش',
  'Celta Vigo': 'سيلتا فيغو',
  'Getafe': 'خيتافي',
  'Girona': 'جيرونا',
  'Granada': 'غرناطة',
  'Las Palmas': 'لاس بالماس',
  'Mallorca': 'مايوركا',
  'Osasuna': 'أوساسونا',
  'Rayo Vallecano': 'رايو فاليكانو',
  'Real Betis': 'ريال بيتيس',
  'Real Madrid': 'ريال مدريد',
  'Real Sociedad': 'ريال سوسيداد',
  'Sevilla': 'إشبيلية',
  'Valencia': 'فالنسيا',
  'Villarreal': 'فياريال',
  'Espanyol': 'إسبانيول',
  'Levante': 'ليفانتي',
  'Elche': 'إلتشي',
  'Oviedo': 'ريال أوفييدو',

  // Serie A & B
  'AC Milan': 'ميلان',
  'AS Roma': 'روما',
  'Atalanta': 'أتالانتا',
  'Bologna': 'بولونيا',
  'Cagliari': 'كالياري',
  'Como': 'كومو',
  'Cremonese': 'كريمونيزي',
  'Empoli': 'إمبولي',
  'Fiorentina': 'فيورنتينا',
  'Frosinone': 'فروزينوني',
  'Genoa': 'جنوى',
  'Inter': 'إنتر ميلان',
  'Juventus': 'يوفنتوس',
  'Lazio': 'لاتسيو',
  'Lecce': 'ليتشي',
  'Monza': 'مونزا',
  'Napoli': 'نابولي',
  'Parma': 'بارما',
  'Pisa': 'بيزا',
  'Roma': 'روما',
  'Salernitana': 'ساليرنيتانا',
  'Sassuolo': 'ساسولو',
  'Torino': 'تورينو',
  'Udinese': 'أودينيزي',
  'Verona': 'هيلاس فيرونا',
  'Hellas Verona': 'هيلاس فيرونا',

  // Bundesliga
  'Augsburg': 'أوغسبورغ',
  'Bayer Leverkusen': 'باير ليفركوزن',
  'Bayern Munich': 'بايرن ميونخ',
  'Bochum': 'بوخوم',
  'Borussia Dortmund': 'بوروسيا دورتموند',
  'Borussia Monchengladbach': 'بوروسيا مونشنغلادباخ',
  'Darmstadt': 'دارمشتات',
  'Eintracht Frankfurt': 'آينتراخت فرانكفورت',
  'FC Cologne': 'كولن',
  'FC Heidenheim': 'هايدنهايم',
  'Freiburg': 'فرايبورغ',
  'Hoffenheim': 'هوفنهايم',
  'Mainz 05': 'ماينتس 05',
  'RB Leipzig': 'لايبزيغ',
  'Stuttgart': 'شتوتغارت',
  'Union Berlin': 'يونيون برلين',
  'Werder Bremen': 'فيردر بريمن',
  'Wolfsburg': 'فولفسبورغ',

  // Ligue 1
  'Brest': 'بريست',
  'Clermont Foot': 'كليرمون فوت',
  'Le Havre': 'لوهافر',
  'Lens': 'لانس',
  'Lille': 'ليل',
  'Lorient': 'لوريان',
  'Lyon': 'أولمبيك ليون',
  'Marseille': 'أولمبيك مارسيليا',
  'Metz': 'ميتز',
  'Monaco': 'موناكو',
  'Montpellier': 'مونبلييه',
  'Nantes': 'نانت',
  'Nice': 'نيس',
  'Paris Saint Germain': 'باريس سان جيرمان',
  'Reims': 'ستاد ريمس',
  'Rennes': 'ستاد رين',
  'Strasbourg': 'ستراسبورغ',
  'Toulouse': 'تولوز',

  // Egyptian Premier League
  'El Geish': 'طلائع الجيش',
  'El Gouna FC': 'الجونة',
  'El Mokawloon': 'المقاولون العرب',
  'Future FC': 'فيوتشر',
  'Ghazl El Mehalla': 'غزل المحلة',
  'Haras El Hodood': 'حرس الحدود',
  'Ismaily SC': 'الإسماعيلي',
  'National Bank of Egypt': 'البنك الأهلي المصري',
  'Petrojet': 'بتروجيت',
  'Pharco': 'فاركو',
  'Al Ahly': 'الأهلي',
  'Zamalek': 'الزمالك',
  'Pyramids FC': 'بيراميدز',
  'Al Masry': 'المصري',
  'Smouha SC': 'سموحة',
  'Enppi': 'إنبي',
  'Al Ittihad': 'الاتحاد', // Also Saudi, but usually context is clear enough

  // Moroccan Botola Pro
  'CODM Meknès': 'النادي المكناسي',
  'CR Khemis Zemamra': 'نهضة الزمامرة',
  'Difaa EL Jadida': 'الدفاع الحسني الجديدي',
  'Hassania Agadir': 'حسنية أكادير',
  'Ittihad Tanger': 'اتحاد طنجة',
  'Kawkab Marrakech': 'الكوكب المراكشي',
  'Maghreb Fès': 'المغرب الفاسي',
  'Olympique Dcheïra': 'أولمبيك الدشيرة',
  'Olympique Safi': 'أولمبيك آسفي',
  'Raja Casablanca': 'الرجاء الرياضي',
  'Renaissance Berkane': 'نهضة بركان',
  'UTS Rabat': 'اتحاد تواركة',
  'Wydad AC': 'الوداد الرياضي',
  'FAR Rabat': 'الجيش الملكي',
  'FUS Rabat': 'الفتح الرياضي',
  'Yacoub El Mansour': 'يعقوب المنصور',

  // League of Ireland
  'Bohemians': 'بوهيميانز',
  'Derry City': 'ديري سيتي',
  'Drogheda United': 'دروهيدا يونايتد',
  'Dundalk': 'دوندولك',
  'Galway United': 'غالواي يونايتد',
  'Shamrock Rovers': 'شامروك روفرز',
  'Shelbourne': 'شيلبورن',
  'Sligo Rovers': 'سليغو روفرز',
  "St Patrick's Athl.": 'سانت باتريكس أثلتيك',
  'Waterford': 'ووترفورد',

  // Egyptian (additional)
  'Kahraba Ismailia': 'كهرباء الإسماعيلية',

  // Others
  'Al Diriyah': 'الدرعية',
  'Al Ula': 'العلا',
  'Racing Club': 'راسينغ كلوب',
  'Corinthians': 'كورينثيانز',
  'Penarol': 'بينارول',
  'U. Catolica': 'أونيفرسيداد كاتوليكا',
  'Barcelona SC': 'برشلونة الإكوادوري',
  'Macara': 'ماكارا',
  'Alianza Atletico': 'أليانزا أتلتيكو',
  'Blooming': 'بلومينغ',
  'Carabobo FC': 'كارابوبو',
  'Caracas FC': 'كاراكاس',
};

/**
 * Reusable utility to safely map API-Football team English names to Arabic names.
 * Falls back to the original English name if the team is not mapped.
 * 
 * @param englishName The original team name from the API
 * @returns The Arabic name or the fallback name
 */
export function getArabicTeamName(englishName: string): string {
  if (englishName in ARABIC_TEAM_MAP) {
    return ARABIC_TEAM_MAP[englishName];
  }
  return englishName;
}
